version: '3.9'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  lint:
    build: .
    volumes:
      - .:/app
    command: flake8 .

  format:
    build: .
    volumes:
      - .:/app
    command: autopep8 . --in-place --recursive --aggressive

volumes:
  postgres_data:
